### ISSUE TITLE
docker container can't run, alaways restart 

### ISSUE THREAD

**Issue by indie21** [hopsoft/docker-graphite-statsd#68]
take a few minutes is seem like a joke ,it already cost my 6 hours to run it .

hahahah .
mac os x ,

docker run -d \  --name graphite \  --restart=always \  -p 80:80 \  -p 2003-2004:2003-2004 \  -p 2023-2024:2023-2024 \  -p 8125:8125/udp \  -p 8126:8126 \ hopsoft/graphite-statsd

*** Killing all processes...
Traceback (most recent call last):
  File "/sbin/my_init", line 346, in <module>
    main(args)
  File "/sbin/my_init", line 265, in main
    export_envvars()
  File "/sbin/my_init", line 88, in export_envvars
    f.write(value)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-9: ordinal not in range(128)

**Comment by indie21** [comment]
add LC_ALL solved the problems

 -e 'LC_ALL=en_US.UTF-8' \
